config: /data1/pengfeigao/BP-MoE/configs/aaai_layer1/base_6xa100.yaml

name: A-HE8

model:
  moe_num_experts: 8
  moe_top_k: 1
  moe_router_use_hidden_state: true
  moe_router_use_patch_entropy: true
  moe_router_entropy_mlp_hidden_dim: 32
